### ISSUE TITLE
Error message when adding reviewers

### ISSUE THREAD

**Issue by spooots** [silvio/gerrit-rust#25]
$ gerrit-rust topic reviewer <topic> -v -r <reviewer@bla.de>
Problem to add 'reviewer@bla.de' as reviewer: JSON error
Problem to add 'reviewer@bla.de' as reviewer: JSON error
$ gerrit-rust --version
gerrit-rust git-v0.1.22
Finally althought the error was displayed, the reviewer was added to the topic changes.

**Comment by silvio** [comment]
Thanks @spooots for reporting this. Maybe a copy/paste mistake but your line doesn't contain the topic name.

Please check against the [latest release], I have [fixed] a problem regarding this. Maybe this was the problem.

[latest release]: https://github.com/silvio/gerrit-rust/releases/tag/v0.1.23
[fixed]: https://github.com/silvio/gerrit-rust/commit/f4cb2a6403f9d501cc0471904bf457b75f57c59e

**Comment by spooots** [comment]
Behaviour with V0.1.23 is fine. I wasn't able to observe the error again :) Thanks !!
